# pyproject.toml

[project]
name = "mat-analyzer"
version = "1.0.0"
description = "A library for analyzing data from universal test machines."
authors = [{ name = "Your Name", email = "you@example.com" }]

[tool.setuptools]
packages = ["analysis_lib"]
